### PR TITLE
Entrypoint options, SR-IOV functionality, CNI libs update

### PR DESCRIPTION
**Pull request by dougbtv**
Includes these upstream PR's: 327, 326, 320, 315, 309, 307, 206

(Note: 206 had been missing previously, found it earlier today)

### CODE REVIEW

**Comment by dougbtv** [comment]
Looking into possible failure in this travis job: https://travis-ci.org/intel/multus-cni/builds/539348872

**Comment by zshi-redhat** [comment]
@dougbtv looks like we are adding test case [commit](https://github.com/openshift/multus-cni/pull/15/commits/f5bb00a5b1e45444236edebd6a638c2cf8dcec0d) for device id assignment but not the real [change](https://github.com/intel/multus-cni/pull/307/commits/ec9f6bb13e53e69a83945044c103ba0b45de1b4f); could you please also include the latter?

**Comment by s1061123** [comment]
/lgtm

@dougbtv thanks!!

**Pull request merged**
