### PR TITLE
Bug 1972167: Updates entrypoint to rebuild kubeconfig when service account token or ca changes

### PR DESCRIPTION
**Pull request by dougbtv**
For hourly rotating svc account tokens

### CODE REVIEW

**Comment by knobunc** [comment]
Moving to valid because the bot is not allowing ON_QA, but would have allowed it when it was MODIFIED.

**Comment by dougbtv** [comment]
/test e2e-aws-upgrade

yo dawg, I hear you like auth and RBAC errors, so while testing your auth error PR, I got an RBAC error for the credentials operator which was forbidden.

(I think it's a flake)

```
Error creating: pods "cloud-credential-operator-8655cbc4d-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/cloud-credential-operator-8655cbc4d -n openshift-cloud-credential-operator happened 14 times
```

**Comment by dougbtv** [comment]
Bummer, here's the thing... I see the error we're trying to fix here, HOWEVER... it's *super* short lived, happens for a single pod, and causes CI to fail. That pod should have another attempt.

```
Jun 18 19:05:54.474108 ip-10-0-255-140 hyperkube[1376]: E0618 19:05:54.474083    1376 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-metrics-daemon-dssbn_openshift-multus_5bf2f56b-aac9-4fae-9767-91fc897f2712_0(dc9df6a5e86b8683ec992397ae781c426ec17bf09af0ea1f84cd1e2662e55176): Multus: [openshift-multus/network-metrics-daemon-dssbn]: error getting pod: Unauthorized"
Jun 18 19:05:54.474498 ip-10-0-255-140 hyperkube[1376]: E0618 19:05:54.474144    1376 kuberuntime_sandbox.go:68] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-metrics-daemon-dssbn_openshift-multus_5bf2f56b-aac9-4fae-9767-91fc897f2712_0(dc9df6a5e86b8683ec992397ae781c426ec17bf09af0ea1f84cd1e2662e55176): Multus: [openshift-multus/network-metrics-daemon-dssbn]: error getting pod: Unauthorized" pod="openshift-multus/network-metrics-daemon-dssbn"
Jun 18 19:05:54.474498 ip-10-0-255-140 hyperkube[1376]: E0618 19:05:54.474169    1376 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-metrics-daemon-dssbn_openshift-multus_5bf2f56b-aac9-4fae-9767-91fc897f2712_0(dc9df6a5e86b8683ec992397ae781c426ec17bf09af0ea1f84cd1e2662e55176): Multus: [openshift-multus/network-metrics-daemon-dssbn]: error getting pod: Unauthorized" pod="openshift-multus/network-metrics-daemon-dssbn"
Jun 18 19:05:54.474498 ip-10-0-255-140 hyperkube[1376]: E0618 19:05:54.474248    1376 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"network-metrics-daemon-dssbn_openshift-multus(5bf2f56b-aac9-4fae-9767-91fc897f2712)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"network-metrics-daemon-dssbn_openshift-multus(5bf2f56b-aac9-4fae-9767-91fc897f2712)\\\": rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-metrics-daemon-dssbn_openshift-multus_5bf2f56b-aac9-4fae-9767-91fc897f2712_0(dc9df6a5e86b8683ec992397ae781c426ec17bf09af0ea1f84cd1e2662e55176): Multus: [openshift-multus/network-metrics-daemon-dssbn]: error getting pod: Unauthorized\"" pod="openshift-multus/network-metrics-daemon-dssbn" podUID=5bf2f56b-aac9-4fae-9767-91fc897f2712
```

But, it's making me question the fix. What really causes us to be unauthenticated.

However, that being said -- this CI failure is sensitive enough that I'm not sure this actually blocker. I think overall the system should work.

**Comment by dougbtv** [comment]
/retest

...worth another try anyway.

**Pull request merged**
