### PR TITLE
Bug 1822803: Add nil check for pod in case of Eventf()

### PR DESCRIPTION
**Pull request by s1061123**

### CODE REVIEW

**Comment by tedyu** [comment]
go vet:
```
##[error]vet: webhook/webhook.go:35:61: NetworkAttachmentDefinition not declared by package types
##[error]Process completed with exit code 2.
```
Not related to this PR.

**Comment by s1061123** [comment]
Docker-build/Go-Build-ppc64le are failed due to CGO_ENABLED=1. Not related to this fix.

**Pull request merged**
