### PR TITLE
Bug 1968625: Use the default socket path in GetResourceClient when unspecified

### PR DESCRIPTION
**Pull request by dougbtv**
Signed-off-by: Peng Liu <pliu@redhat.com>

### CODE REVIEW

**Review by s1061123 — APPROVED** [review]
/lgtm

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws-upgrade

This job was broken by the rebase and will not work until https://github.com/openshift/cluster-network-operator/pull/1118 ships in stable

**Pull request merged**
