### PR TITLE
[WIP] Test entrypoint ocicni

### PR DESCRIPTION
**Pull request by dougbtv**

### CODE REVIEW

**Comment by dougbtv** [comment]
/hold

...this is a test.

**Comment by squeed** [comment]
@dougbtv If you look at the test artifacts, the nodes never went ready. Something is wrong.

**Comment by dougbtv** [comment]
Thanks @squeed -- been using this is a sort of test bed to see what happens when I modify the entrypoint script. First attempt was to try "the workaround" -- which is just to use the same `"name":` field in the configs (using the `--override-network-name` parameter, which just copies the `name` field from the source config to the generated config) -- which didn't work right out of the box. For comparison, I took that out, and... still have failures, oddly enough.

**Comment by dougbtv** [comment]
/retest

...this one is a revert to the original entrypoint.sh, desiring to see a clean run. last run, installer logs looks like it never had the API up.

**Pull request closed without merging**
