### PR TITLE
OCPBUGS-37991: Downstream sync to address multiple interface returns in network-status annotation

### PR DESCRIPTION
**Pull request by dougbtv**
Notably includes https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/releases/tag/v1.7.1 in order to fix up status annotations when a delegated plugin has multiple pod interfaces in the CNI result.

### CODE REVIEW

**Comment by dougbtv** [comment]
/title OCPBUGS-37991: Downstream sync to address multiple interface returns in network-status annotation

**Comment by dougbtv** [comment]
/retitle OCPBUGS-37991: Downstream sync to address multiple interface returns in network-status annotation

**Comment by bpickard22** [comment]
Quick note, this is my first downstream merge review so if I miss anything sorry in advance

**Pull request merged**
