### PR TITLE
Multus CNI updates for OCP 4.6

### PR DESCRIPTION
**Pull request by dougbtv**
Notably, this includes updates to vendored packages.

### CODE REVIEW

**Comment by smarterclayton** [comment]
How did this merge with the network name break?  It seems like this should have failed to merge?

**Comment by smarterclayton** [comment]
This appears to be https://github.com/kubernetes/kubernetes/issues/58711, which was fixed in 3.11 in openshift/origin@a6e1db66b9d56f11772b5f39925c408006371e92 but has not been deployed to api.ci.  We either need to update the node or stop running pods on that.

**Comment by dougbtv** [comment]
@smarterclayton thanks for the heads up -- I might need a little more info.

> How did this merge with the network name break? It seems like this should have failed to merge?

I'm unsure where this test may be, so I can't answer how. I did look at your reference of https://github.com/openshift/origin/commit/a6e1db66b9d56f11772b5f39925c408006371e92 and I was specifically looking for any mention of using the `networks-status` annotation, specifically the changes made in this upstream PR https://github.com/intel/multus-cni/pull/515/files (which looks the closest to the description of "with the network name break") from this particular change set. However 

Regarding https://github.com/intel/multus-cni/pull/515/files -- what this changes specifically the contents of an annotation on pods as processed by Multus, an annotation titled: `k8s.v1.cni.cncf.io/networks-status` (which is defined by the [NPWG spec](https://github.com/k8snetworkplumbingwg/multi-net-spec/tree/master/v1.1) in section 5) this contains a JSON field, titled "name", which used to refer to the name of a network attachment definition. This change makes it so instead of referring to the name of a network attachment definition, it refers to the name and namespace of the network attachment definition, e.g. if you have a net-attach-def named `bar` in a namespace called `foo` the results of the name field of this JSON object will be `foo/bar` (whereas previously it was just `bar`).

In the meanwhile, @s1061123 is putting in a PR which reverts this change to `k8s.v1.cni.cncf.io/networks-status` as a stop-gap here, in case CI is broken elsewhere. @s1061123 also noted that he saw an inconsistency in CI (my notes suffered here, but, I think it was depending on a bot re-run? unsure. it was alarming enough to make us consider the revert).

**Comment by s1061123** [comment]
@smarterclayton @dougbtv Filed revert PR as https://github.com/openshift/multus-cni/pull/72 .

**Comment by fedepaol** [comment]
@smarterclayton looks line the e2e-aws lane never passed: https://prow.ci.openshift.org/pr-history/?org=openshift&repo=multus-cni&pr=71 .
The run the bot says was successful lasted 5 seconds: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_multus-cni/71/pull-ci-openshift-multus-cni-master-e2e-aws/1287051359769595904

**Pull request merged**
