### PR TITLE
Adds readinessindicatorfile check on CNI DEL

### PR DESCRIPTION
**Pull request by dougbtv**
This adds the readiness check on CNI DEL. 

This is a WIP until I can have some maintainers discussion about it, as well.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Running an upgrade test on this with both sides of the PR https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/23818

**Comment by danehans** [comment]
/cherrypick release-4.4

This is a test to see if this PR fixes failed 4.4 GCP upgrade CI jobs.

**Comment by dougbtv** [comment]
/retitle Adds readinessindicatorfile check on CNI DEL

**Pull request merged**
