### PR TITLE
Bug 1927264: Vendor bump for client-go fixes

### PR DESCRIPTION
**Pull request by dougbtv**
From Antonio:

The kubernetes dependencies were too old and missing an important fix in client-go, that deals with hanging connections, something that we can see A LOT in the CI XD

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox...

```
error getting pod: Get "https://[api-int.ci-op-tdqc7nvw-f23e1.gcp-2.ci.openshift.org]:6443/api/v1/namespaces/<ns>/pods/<pod>?timeout=1m0s": dial tcp 10.0.0.2:6443: i/o timeout
```

----

**Note:** This PR required a large number of changes from upstream to be synced due to the upstream namespace being changed. In order to have the packages vendor correctly, a large number of commits spanning this ranged were necessary in order to get this vendor bump.

### CODE REVIEW

**Comment by dougbtv** [comment]
/retest

image build looks like a flake?

**Comment by dougbtv** [comment]
/title Bug 1927264: Vendor bump for client-go fixes

**Comment by dougbtv** [comment]
/retitle Bug 1927264: Vendor bump for client-go fixes

**Comment by s1061123** [comment]
/lgtm

Thanks, Doug!

**Pull request merged**
