### PR TITLE
Restore 112: with cni del warning

### PR DESCRIPTION
**Pull request by dougbtv**
The restores #112 and also includes a proposed patch for the CNI DEL path to warn on pod UID mismatch and operate on cache / netns, as opposed to name/namespace in this case.

**NOTE**: This is a WIP change for testing purposes, it still needs to go upstream first.

### CODE REVIEW

**Comment by dgoodwin** [comment]
@petr-muller could you kick off the payload tests against this PR? it caused a regression that was caught by aggregated jobs, and Doug has included a fix attempt in this PR.

**Comment by deads2k** [comment]
ask if @petr-muller can run 10x `periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade` and ask me to aggregate it for you for a check on monday.

**Comment by petr-muller** [comment]
Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-azure-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=multus-cni-118-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade
Aggregation ID: `71cfa802-4b80-11ec-b816-f875a4a87b27`

**Comment by deads2k** [comment]
This PR passed our aggregation targets.

**Pull request merged**
