### PR TITLE
OCPBUGS-28230: enforce termination message policy on all platform pods

### PR DESCRIPTION
**Pull request by deads2k**
This will include the last few log lines on container crashes to assist in debugging.

### CODE REVIEW

**Comment by s1061123** [comment]
@deads2k thank you for the PR, but these files are not used in OCP, actually. These files are just copied from upstream's example yaml and actual files is in cluster network operator. Your CNO's PR(https://github.com/openshift/cluster-network-operator/pull/2224) already cares of that, so if you don't mind it, I'd like to close this PR.

**Comment by zshi-redhat** [comment]
@deads2k  The Multus manifests are managed in CNO repo for OpenShift deployment. I see you already had a PR merged in CNO which covers Multus: https://github.com/openshift/cluster-network-operator/pull/2224. I think we can close this PR.

**Comment by deads2k** [comment]
> @deads2k thank you for the PR, but these files are not used in OCP, actually. These files are just copied from upstream's example yaml and actual files is in cluster network operator. Your CNO's PR([openshift/cluster-network-operator#2224](https://github.com/openshift/cluster-network-operator/pull/2224)) already cares of that, so if you don't mind it, I'd like to close this PR.

Cool, thanks.

**Pull request closed without merging**
