### PR TITLE
Removes configuration invalidation

### PR DESCRIPTION
**Pull request by dougbtv**
Experimental commit, do not merge. Hacks in method for not removing config invalidation.

### CODE REVIEW

**Comment by smarterclayton** [comment]
/retest

There's a very good chance that this fixed the openshift-apiserver going unavailable during upgrades (https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_multus-cni/50/pull-ci-openshift-multus-cni-master-e2e-aws-upgrade/77) - since that test has consistently failed since it was introduced, but it's passed here.  Which is excellent news - @deads2k were there any other changes landed in the last few days that could have made this start passing, or can we infer causation from this change?

**Comment by smarterclayton** [comment]
This time the api was down for only 11s, which is a big improvement.

I think this passes the bar for me "value in coasting" > "slightly complexity increase of cleaning up".

So I'm supportive of this going into 4.5, us assessing it, and then back porting after a few days/week of improvement.

**Comment by smarterclayton** [comment]
It looks like the upgrade is broken at 79% and multus container is crash looping:

```
/entrypoint.sh: line 17: syntax error near unexpected token `}'
```

**Comment by dougbtv** [comment]
Thanks for the eyes on the shell script error. I've got a new commit up that should address that.

If this look OK with this one, I'll put together a final product that can go both upstream/downstream.

**Comment by smarterclayton** [comment]
I'm going to run an upgrade job in the reverse order (from this PR to master) to see that it fixes the disruption (since the current path won't because we upgrade from not this code to having this code and the check is on teardown).

**Comment by smarterclayton** [comment]
Ok, https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/19234/build-log.txt (in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/19234) looks like it successfully met the criteria (node didn't go notready during multus upgrade).

This improves the outcome of upgrade by reducing unrelated failures, so lgtm in terms of approach (still needs code review).

**Comment by smarterclayton** [comment]
Do we need to change this code?  Can't we just set `MULTUS_CLEANUP_CONFIG_ON_EXIT=false` on the multus pod via the CNO?

**Comment by smarterclayton** [comment]
/hold

for the question

**Comment by s1061123** [comment]
As far as I look the code, following line does not have "if $MULTUS_CLEANUP_CONFIG_ON_EXIT" so need to modify diffs to keep the flag.

https://github.com/openshift/multus-cni/pull/50/files#diff-5b59de2786d0584351695a727ff60b59L389-L392

**Comment by dougbtv** [comment]
Two parts to the cleanup, invalidating the config (which this commit removes) and the other -- regenerating the config after an sdn upgrade (which this does not remove) so... I recommend we move forward with what's here (ok to merge but we'll need to sync with upstream later)

**Pull request merged**
